const SUPABASE_URL='https://kzhklbtdyzinfacaotuh.supabase.co';
const SUPABASE_KEY='sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY); const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let state={user:null,elections:[],candidates:[],voters:[],votes:[],adminTab:'elections',voterSession:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>d?new Date(d).toLocaleString('tr-TR'):'—';
function setPage(p){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+p).classList.remove('hidden');$('#pageTitle').textContent={home:'Online Seçim Sistemi',vote:'Oy Kullan',results:'Seçim Sonuçları',admin:'Yönetim Paneli'}[p]||'';render();}
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
async function load(){const {data:{user}}=await db.auth.getUser();state.user=user||null;document.body.classList.toggle('admin',!!state.user);$('.adminOnly')?.classList.toggle('hidden',!!state.user===false);const [e,c]=await Promise.all([db.from('elections').select('*').order('created_at',{ascending:false}),db.from('candidates').select('*').order('sort_order')]);state.elections=e.data||[];state.candidates=c.data||[];if(state.user){const [v,vo]=await Promise.all([db.from('voters').select('*').order('name'),db.from('votes').select('*, voters(name), candidates(name)').order('created_at',{ascending:false})]);state.voters=v.data||[];state.votes=vo.data||[]}renderAuth();render();}
function activeElection(){const now=Date.now();return state.elections.find(e=>e.status==='open'&&(!e.start_at||new Date(e.start_at)<=now)&&(!e.end_at||new Date(e.end_at)>=now));}
function renderAuth(){$('#auth').innerHTML=state.user?`<span class="muted">👑 Yönetici</span> <button class="authbtn" id="logout">Çıkış</button>`:`<button class="authbtn" id="login">Yönetici Girişi</button>`;$('#login')?.addEventListener('click',login);$('#logout')?.addEventListener('click',async()=>{await db.auth.signOut();await load()})}
function render(){renderHome();renderVote();renderResults();if(state.user)renderAdmin();}
function renderHome(){const e=activeElection();$('#homeContent').innerHTML=e?`<div class="card"><div class="cardhead"><div><h3>${esc(e.title)}</h3><p class="muted">${esc(e.description||'Aktif seçim')}</p></div><span class="pill open">🟢 AKTİF</span></div><p class="muted">Bitiş: ${fmt(e.end_at)}</p><button class="primary" id="goVote">Oy Kullanmaya Git →</button></div>`:`<div class="card empty">Şu anda aktif bir seçim bulunmuyor.</div>`;$('#goVote')?.addEventListener('click',()=>setPage('vote'))}
function renderVote(){const e=activeElection();if(!e){$('#voteContent').innerHTML='<div class="card empty">Şu anda oy kullanıma açık bir seçim yok.</div>';return}const cs=state.candidates.filter(c=>c.election_id===e.id); if(!state.voterSession||state.voterSession.election_id!==e.id){$('#voteContent').innerHTML=`<div class="card codebox"><h3>${esc(e.title)}</h3><p class="muted">Oy kullanmak için size verilen erişim kodunu girin.</p><input id="voterCode" placeholder="Erişim kodunuz"><button class="primary" id="verifyCode">Devam Et</button><div id="codeMsg"></div></div>`;$('#verifyCode').onclick=verifyCode;return}$('#voteContent').innerHTML=`<div class="card"><div class="notice">${esc(state.voterSession.name)}, oy verdikten sonra oyunuzu değiştiremezsiniz.</div><h3>${esc(e.title)}</h3><div class="candidateGrid">${cs.map(c=>`<div class="candidate" data-candidate="${c.id}">${c.photo_url?`<img src="${esc(c.photo_url)}">`:''}<h3>${esc(c.name)}</h3><p class="muted">${esc(c.description||'')}</p><button class="secondary choose" data-id="${c.id}">Bu adayı seç</button></div>`).join('')}</div></div>`;$$('.choose').forEach(b=>b.onclick=()=>confirmVote(e,+b.dataset.id));}
async function verifyCode(){const code=$('#voterCode').value.trim();if(!code)return;const e=activeElection();const {data,error}=await db.rpc('get_voter_by_code',{p_election_id:e.id,p_access_code:code});if(error||!data?.length){$('#codeMsg').innerHTML='<p class="notice">Kod bulunamadı veya bu seçim için yetkiniz yok.</p>';return}state.voterSession=data[0];renderVote();}
function confirmVote(e,cid){const c=state.candidates.find(x=>x.id===cid);modal(`<h3>Oyunu Onayla</h3><p><b>${esc(c.name)}</b> adayına oy vermek üzeresin.</p><p class="muted">Bu işlemden sonra oyun değiştirilemez.</p><div class="actions"><button class="secondary" id="cancel">Vazgeç</button><button class="primary" id="cast">Oyumu Kesinleştir</button></div>`);$('#cancel').onclick=closeModal;$('#cast').onclick=async()=>{const {error}=await db.rpc('cast_vote',{p_election_id:e.id,p_candidate_id:cid,p_access_code:state.voterSession.access_code});if(error){alert(error.message);return}closeModal();state.voterSession=null;$('#voteContent').innerHTML='<div class="card empty"><h3>🎉 Oyun kaydedildi</h3><p>Katılımınız için teşekkür ederiz.</p></div>';};}
async function renderResults(){const closed=state.elections.find(e=>e.status==='closed'&&e.results_visible)||state.elections.find(e=>e.results_visible);if(!closed){$('#resultsContent').innerHTML='<div class="card empty">Sonuçları açıklanmış bir seçim bulunmuyor.</div>';return}const {data}=await db.rpc('election_results',{p_election_id:closed.id});const rows=data||[];const total=rows.reduce((a,x)=>a+Number(x.vote_count||0),0);const winner=rows[0];$('#resultsContent').innerHTML=`${winner?`<div class="winner">🏆<strong>${esc(winner.name)}</strong><div>Seçimi kazandı</div><p>${winner.vote_count} oy • ${total?((winner.vote_count*100/total).toFixed(1)):0}%</p></div>`:''}<div class="card"><h3>${esc(closed.title)}</h3><p class="muted">Toplam kullanılan oy: ${total}</p>${rows.map((r,i)=>{let pct=total?(r.vote_count*100/total):0;return `<div class="resultRow"><div class="resultMeta"><span>${i+1}. ${esc(r.name)}</span><b>${r.vote_count} oy • ${pct.toFixed(1)}%</b></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div></div>`}).join('')}</div>`}
function renderAdmin(){const e=state.elections[0];if(state.adminTab==='elections')$('#adminContent').innerHTML=`<div class="cardhead"><div><h3>Seçimler</h3><p class="muted">Seçim oluşturun ve durumunu yönetin.</p></div><button class="primary" id="newElection">+ Yeni Seçim</button></div><table><tr><th>Seçim</th><th>Durum</th><th>Bitiş</th><th></th></tr>${state.elections.map(x=>`<tr><td><b>${esc(x.title)}</b><br><span class="muted">${esc(x.description||'')}</span></td><td><span class="pill ${x.status}">${x.status}</span></td><td>${fmt(x.end_at)}</td><td><button class="secondary editElection" data-id="${x.id}">Düzenle</button></td></tr>`).join('')}</table>`;
else if(state.adminTab==='candidates')$('#adminContent').innerHTML=`<div class="cardhead"><div><h3>Adaylar</h3><p class="muted">Aday ekleyin veya kaldırın.</p></div><button class="primary" id="newCandidate">+ Aday Ekle</button></div>${adminSelect()}<div class="candidateGrid">${state.candidates.filter(c=>!e||c.election_id===e.id).map(c=>`<div class="candidate"><h3>${esc(c.name)}</h3><p class="muted">${esc(c.description||'')}</p><button class="danger delCandidate" data-id="${c.id}">Sil</button></div>`).join('')||'<div class="empty">Henüz aday yok.</div>'}</div>`;
else if(state.adminTab==='voters')$('#adminContent').innerHTML=`<div class="cardhead"><div><h3>Oy Kullanıcıları</h3><p class="muted">Her kişi için erişim kodu oluşturun.</p></div><button class="primary" id="newVoter">+ Oy Kullanıcı Ekle</button></div>${adminSelect()}<table><tr><th>Ad</th><th>E-posta</th><th>Kod</th><th>Durum</th><th></th></tr>${state.voters.filter(v=>!e||v.election_id===e.id).map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.email||'—')}</td><td><b>${esc(v.access_code||'')}</b></td><td>${v.has_voted?'✅ Oy kullandı':'⏳ Bekliyor'}</td><td><button class="danger delVoter" data-id="${v.id}">Sil</button></td></tr>`).join('')}</table>`;
else $('#adminContent').innerHTML=`<h3>Oy Kayıtları</h3><p class="muted">Bu alan yalnızca yöneticiye görünür.</p>${adminSelect()}<table><tr><th>Oy Veren</th><th>Aday</th><th>Zaman</th></tr>${state.votes.filter(v=>!e||v.election_id===e.id).map(v=>`<tr><td>${esc(v.voters?.name||'')}</td><td>${esc(v.candidates?.name||'')}</td><td>${fmt(v.created_at)}</td></tr>`).join('')}</table>`;
$$('.tab').forEach(t=>t.onclick=()=>{state.adminTab=t.dataset.adminTab;$$('.tab').forEach(x=>x.classList.toggle('active',x===t));renderAdmin()});$('#newElection')?.addEventListener('click',newElection);$('#newCandidate')?.addEventListener('click',newCandidate);$('#newVoter')?.addEventListener('click',newVoter);$$('.editElection').forEach(b=>b.onclick=()=>editElection(+b.dataset.id));$$('.delCandidate').forEach(b=>b.onclick=()=>del('candidates',+b.dataset.id));$$('.delVoter').forEach(b=>b.onclick=()=>del('voters',+b.dataset.id));}
function adminSelect(){return state.elections.length?`<div class="notice">Yönetilen seçim: <b>${esc(state.elections[0].title)}</b></div>`:'<div class="notice">Önce bir seçim oluşturun.</div>'}
function newElection(){modal(`<h3>Yeni Seçim</h3><input id="xTitle" placeholder="Seçim adı"><textarea id="xDesc" placeholder="Açıklama"></textarea><label>Başlangıç</label><input id="xStart" type="datetime-local"><label>Bitiş</label><input id="xEnd" type="datetime-local"><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="save">Oluştur</button></div>`);$('#cancel').onclick=closeModal;$('#save').onclick=async()=>{let {error}=await db.from('elections').insert({title:$('#xTitle').value,description:$('#xDesc').value,start_at:$('#xStart').value||null,end_at:$('#xEnd').value||null,status:'draft'});if(error)return alert(error.message);closeModal();load()}}
function editElection(id){const e=state.elections.find(x=>x.id===id);modal(`<h3>Seçimi Düzenle</h3><input id="xTitle" value="${esc(e.title)}"><textarea id="xDesc">${esc(e.description||'')}</textarea><select id="xStatus"><option value="draft">Taslak</option><option value="open">Açık</option><option value="closed">Kapalı</option></select><label><input type="checkbox" id="xVisible" ${e.results_visible?'checked':''}> Sonuçları göster</label><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="save">Kaydet</button></div>`);$('#xStatus').value=e.status;$('#cancel').onclick=closeModal;$('#save').onclick=async()=>{let {error}=await db.from('elections').update({title:$('#xTitle').value,description:$('#xDesc').value,status:$('#xStatus').value,results_visible:$('#xVisible').checked}).eq('id',id);if(error)return alert(error.message);closeModal();load()}}
function newCandidate(){const e=state.elections[0];if(!e)return alert('Önce seçim oluştur.');modal(`<h3>Aday Ekle</h3><input id="xName" placeholder="Aday adı"><textarea id="xDesc" placeholder="Açıklama"></textarea><input id="xPhoto" placeholder="Fotoğraf URL (isteğe bağlı)"><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="save">Ekle</button></div>`);$('#cancel').onclick=closeModal;$('#save').onclick=async()=>{let {error}=await db.from('candidates').insert({election_id:e.id,name:$('#xName').value,description:$('#xDesc').value,photo_url:$('#xPhoto').value||null});if(error)return alert(error.message);closeModal();load()}}
function newVoter(){const e=state.elections[0];if(!e)return alert('Önce seçim oluştur.');modal(`<h3>Oy Kullanıcı Ekle</h3><input id="xName" placeholder="Ad soyad"><input id="xMail" placeholder="E-posta (isteğe bağlı)"><input id="xCode" placeholder="Erişim kodu"><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="save">Ekle</button></div>`);$('#cancel').onclick=closeModal;$('#save').onclick=async()=>{let {error}=await db.from('voters').insert({election_id:e.id,name:$('#xName').value,email:$('#xMail').value||null,access_code:$('#xCode').value});if(error)return alert(error.message);closeModal();load()}}
async function del(table,id){if(!confirm('Silmek istediğine emin misin?'))return;let {error}=await db.from(table).delete().eq('id',id);if(error)return alert(error.message);load()}
async function login(){modal(`<h3>Yönetici Girişi</h3><input id="email" type="email" placeholder="E-posta"><input id="password" type="password" placeholder="Şifre"><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="doLogin">Giriş</button></div>`);$('#cancel').onclick=closeModal;$('#doLogin').onclick=async()=>{let {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return alert(error.message);closeModal();load()}}
$$('.nav').forEach(b=>b.onclick=()=>{if(b.dataset.page==='admin'&&!state.user)return login();setPage(b.dataset.page)});$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};load();
