const SUPABASE_URL='https://kzhklbtdyzinfacaotuh.supabase.co';
const SUPABASE_KEY='sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaults={brand_name:'Yüksek Şuura',brand_subtitle:'Online Seçim',page_title:'Online Seçim Sistemi',page_subtitle:'Kulüp ve topluluk seçimlerinizi güvenle yönetin.',hero_kicker:'YÜKSEK ŞUURA',hero_title:'Online Seçim Sistemi',hero_text:'Aktif seçimleri görüntüleyin, yetkiniz varsa oyunuzu kullanın ve sonuçları takip edin.',home_empty_text:'Şu anda aktif bir seçim bulunmuyor.',vote_empty_text:'Şu anda oy kullanıma açık bir seçim yok.',results_empty_text:'Sonuçları açıklanmış bir seçim bulunmuyor.'};
let state={user:null,elections:[],candidates:[],voters:[],votes:[],settings:{...defaults},adminTab:'elections',voterSession:null,selectedElectionId:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>d?new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'—';
const toLocalInput=d=>{if(!d)return ''; const x=new Date(d); const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(x); const p=Object.fromEntries(parts.map(v=>[v.type,v.value])); return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`};
const localToISO=v=>v?new Date(v).toISOString():null;
function modal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function setPage(p){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$$('.page').forEach(x=>x.classList.add('hidden'));$('#'+p).classList.remove('hidden');const names={home:state.settings.page_title,vote:'Oy Kullan',results:'Seçim Sonuçları',admin:'Yönetim Paneli'};$('#pageTitle').textContent=names[p]||'';render();}
function applySettings(){const s=state.settings;$('#brandName').textContent=s.brand_name;$('#brandSubtitle').textContent=s.brand_subtitle;$('#pageTitle').textContent=s.page_title;$('#pageSub').textContent=s.page_subtitle;$('#heroKicker').textContent=s.hero_kicker;$('#heroTitle').textContent=s.hero_title;$('#heroText').textContent=s.hero_text;document.title=`${s.brand_name} | ${s.page_title}`;}
async function load(){const [{data:{user}},{data:settings},{data:e},{data:c}]=await Promise.all([db.auth.getUser(),db.from('election_settings').select('*').eq('id',1).maybeSingle(),db.from('elections').select('*').order('created_at',{ascending:false}),db.from('candidates').select('*').order('sort_order')]);state.user=user||null;state.settings={...defaults,...(settings||{})};state.elections=e||[];state.candidates=c||[];if(!state.selectedElectionId&&state.elections[0])state.selectedElectionId=state.elections[0].id;if(state.selectedElectionId&&!state.elections.some(x=>x.id===state.selectedElectionId))state.selectedElectionId=state.elections[0]?.id||null;if(state.user){const [v,vo]=await Promise.all([db.from('voters').select('*').order('name'),db.from('votes').select('*, voters(name), candidates(name)').order('created_at',{ascending:false})]);state.voters=v||[];state.votes=vo||[]}applySettings();renderAuth();render();}
function selectedElection(){return state.elections.find(e=>e.id===state.selectedElectionId)||state.elections[0]||null}
function activeElection(){const now=Date.now();return state.elections.find(e=>e.status==='open'&&(!e.start_at||new Date(e.start_at).getTime()<=now)&&(!e.end_at||new Date(e.end_at).getTime()>=now));}
function renderAuth(){document.body.classList.toggle('admin',!!state.user);$('.adminOnly').classList.toggle('hidden',!state.user);$('#auth').innerHTML=state.user?`<span class="muted">👑 Yönetici</span> <button class="authbtn" id="logout">Çıkış</button>`:`<button class="authbtn" id="login">Yönetici Girişi</button>`;$('#login')?.addEventListener('click',login);$('#logout')?.addEventListener('click',async()=>{await db.auth.signOut();await load()})}
function render(){renderHome();renderVote();renderResults();if(state.user)renderAdmin();}
function renderHome(){const e=activeElection();$('#homeContent').innerHTML=e?`<div class="card"><div class="cardhead"><div><h3>${esc(e.title)}</h3><p class="muted">${esc(e.description||'Aktif seçim')}</p></div><span class="pill open">🟢 AKTİF</span></div><div class="timegrid"><span>🟢 Başlangıç: <b>${fmt(e.start_at)}</b></span><span>🔴 Bitiş: <b>${fmt(e.end_at)}</b></span></div><button class="primary" id="goVote">Oy Kullanmaya Git →</button></div>`:`<div class="card empty">${esc(state.settings.home_empty_text)}</div>`;$('#goVote')?.addEventListener('click',()=>setPage('vote'));}
function renderVote(){const e=activeElection();if(!e){$('#voteContent').innerHTML=`<div class="card empty">${esc(state.settings.vote_empty_text)}</div>`;return}const cs=state.candidates.filter(c=>c.election_id===e.id);if(!state.voterSession||state.voterSession.election_id!==e.id){$('#voteContent').innerHTML=`<div class="card codebox"><h3>${esc(e.title)}</h3><p class="muted">Oy kullanmak için size verilen erişim kodunu girin.</p><input id="voterCode" placeholder="Erişim kodunuz"><button class="primary" id="verifyCode">Devam Et</button><div id="codeMsg"></div></div>`;$('#verifyCode').onclick=verifyCode;return}$('#voteContent').innerHTML=`<div class="card"><div class="notice">${esc(state.voterSession.name)}, oy verdikten sonra oyunuzu değiştiremezsiniz.</div><h3>${esc(e.title)}</h3><div class="candidateGrid">${cs.map(c=>`<div class="candidate">${c.photo_url?`<img src="${esc(c.photo_url)}">`:''}<h3>${esc(c.name)}</h3><p class="muted">${esc(c.description||'')}</p><button class="secondary choose" data-id="${c.id}">Bu adayı seç</button></div>`).join('')}</div></div>`;$$('.choose').forEach(b=>b.onclick=()=>confirmVote(e,+b.dataset.id));}
async function verifyCode(){const code=$('#voterCode').value.trim();if(!code)return;const e=activeElection();const {data,error}=await db.rpc('get_voter_by_code',{p_election_id:e.id,p_access_code:code});if(error||!data?.length){$('#codeMsg').innerHTML='<p class="notice">Kod bulunamadı, daha önce oy kullanıldı veya bu seçim için yetkiniz yok.</p>';return}state.voterSession=data[0];renderVote();}
function confirmVote(e,cid){const c=state.candidates.find(x=>x.id===cid);modal(`<h3>Oyunu Onayla</h3><p><b>${esc(c.name)}</b> adayına oy vermek üzeresin.</p><p class="muted">Bu işlemden sonra oyun değiştirilemez.</p><div class="actions"><button class="secondary" id="cancel">Vazgeç</button><button class="primary" id="cast">Oyumu Kesinleştir</button></div>`);$('#cancel').onclick=closeModal;$('#cast').onclick=async()=>{const {error}=await db.rpc('cast_vote',{p_election_id:e.id,p_candidate_id:cid,p_access_code:state.voterSession.access_code});if(error){alert(error.message);return}closeModal();state.voterSession=null;$('#voteContent').innerHTML='<div class="card empty"><h3>🎉 Oyun kaydedildi</h3><p>Katılımınız için teşekkür ederiz.</p></div>';};}
async function renderResults(){const closed=state.elections.find(e=>e.status==='closed'&&e.results_visible)||state.elections.find(e=>e.results_visible);if(!closed){$('#resultsContent').innerHTML=`<div class="card empty">${esc(state.settings.results_empty_text)}</div>`;return}const {data}=await db.rpc('election_results',{p_election_id:closed.id});const rows=data||[], total=rows.reduce((a,x)=>a+Number(x.vote_count||0),0), winner=rows[0];$('#resultsContent').innerHTML=`${winner?`<div class="winner">🏆<strong>${esc(winner.name)}</strong><div>Seçimi kazandı</div><p>${winner.vote_count} oy • ${total?((winner.vote_count*100/total).toFixed(1)):0}%</p></div>`:''}<div class="card"><h3>${esc(closed.title)}</h3><p class="muted">Toplam kullanılan oy: ${total}</p>${rows.map((r,i)=>{const pct=total?(r.vote_count*100/total):0;return `<div class="resultRow"><div class="resultMeta"><span>${i+1}. ${esc(r.name)}</span><b>${r.vote_count} oy • ${pct.toFixed(1)}%</b></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div></div>`}).join('')}</div>`}
function electionPicker(){return state.elections.length?`<div class="picker"><label>Yönetilecek seçim</label><select id="electionPicker">${state.elections.map(e=>`<option value="${e.id}" ${e.id===state.selectedElectionId?'selected':''}>${esc(e.title)} — ${e.status}</option>`).join('')}</select></div>`:''}
function bindPicker(){const p=$('#electionPicker');if(p)p.onchange=()=>{state.selectedElectionId=+p.value;renderAdmin()}}
function renderAdmin(){const e=selectedElection();const tab=state.adminTab;if(tab==='elections')$('#adminContent').innerHTML=`<div class="cardhead"><div><h3>Seçimler</h3><p class="muted">Seçimi oluştur, tarihlerini belirle ve aktif et.</p></div><button class="primary" id="newElection">+ Yeni Seçim</button></div><table><tr><th>Seçim</th><th>Durum</th><th>Başlangıç</th><th>Bitiş</th><th></th></tr>${state.elections.map(x=>`<tr><td><b>${esc(x.title)}</b><br><span class="muted">${esc(x.description||'')}</span></td><td><span class="pill ${x.status}">${x.status}</span></td><td>${fmt(x.start_at)}</td><td>${fmt(x.end_at)}</td><td><button class="secondary editElection" data-id="${x.id}">Düzenle</button> <button class="danger delElection" data-id="${x.id}">Sil</button></td></tr>`).join('')}</table>`;
else if(tab==='candidates')$('#adminContent').innerHTML=`<div class="cardhead"><div><h3>Adaylar</h3><p class="muted">Adayları seçtiğin seçime ekle.</p></div><button class="primary" id="newCandidate">+ Aday Ekle</button></div>${electionPicker()}<div class="candidateGrid">${state.candidates.filter(c=>e&&c.election_id===e.id).map(c=>`<div class="candidate">${c.photo_url?`<img src="${esc(c.photo_url)}">`:''}<h3>${esc(c.name)}</h3><p class="muted">${esc(c.description||'')}</p><button class="danger delCandidate" data-id="${c.id}">Sil</button></div>`).join('')||'<div class="empty">Henüz aday yok.</div>'}</div>`;
else if(tab==='voters')$('#adminContent').innerHTML=`<div class="cardhead"><div><h3>Oy Kullanıcıları</h3><p class="muted">Oy kullanacak kişileri ve kodlarını yönet.</p></div><button class="primary" id="newVoter">+ Oy Kullanıcı Ekle</button></div>${electionPicker()}<table><tr><th>Ad</th><th>E-posta</th><th>Kod</th><th>Durum</th><th></th></tr>${state.voters.filter(v=>e&&v.election_id===e.id).map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.email||'—')}</td><td><b>${esc(v.access_code||'')}</b></td><td>${v.has_voted?'✅ Oy kullandı':'⏳ Bekliyor'}</td><td><button class="danger delVoter" data-id="${v.id}">Sil</button></td></tr>`).join('')}</table>`;
else if(tab==='votes')$('#adminContent').innerHTML=`<h3>Oy Kayıtları</h3><p class="muted">Bu alan yalnızca yöneticiye görünür.</p>${electionPicker()}<table><tr><th>Oy Veren</th><th>Aday</th><th>Zaman</th></tr>${state.votes.filter(v=>e&&v.election_id===e.id).map(v=>`<tr><td>${esc(v.voters?.name||'')}</td><td>${esc(v.candidates?.name||'')}</td><td>${fmt(v.created_at)}</td></tr>`).join('')}</table>`;
else $('#adminContent').innerHTML=settingsForm();
$$('.tab').forEach(t=>t.onclick=()=>{state.adminTab=t.dataset.adminTab;$$('.tab').forEach(x=>x.classList.toggle('active',x===t));renderAdmin()});bindPicker();$('#newElection')?.addEventListener('click',newElection);$('#newCandidate')?.addEventListener('click',newCandidate);$('#newVoter')?.addEventListener('click',newVoter);$('#saveSettings')?.addEventListener('click',saveSettings);$$('.editElection').forEach(b=>b.onclick=()=>editElection(+b.dataset.id));$$('.delElection').forEach(b=>b.onclick=()=>del('elections',+b.dataset.id));$$('.delCandidate').forEach(b=>b.onclick=()=>del('candidates',+b.dataset.id));$$('.delVoter').forEach(b=>b.onclick=()=>del('voters',+b.dataset.id));}
function settingsForm(){const s=state.settings;const fields=[['brand_name','Sol üst kurum adı'],['brand_subtitle','Sol üst alt yazı'],['page_title','Üst sayfa başlığı'],['page_subtitle','Üst sayfa açıklaması'],['hero_kicker','Banner küçük yazı'],['hero_title','Banner ana başlığı'],['hero_text','Banner açıklaması'],['home_empty_text','Ana sayfa boş mesajı'],['vote_empty_text','Oy sayfası boş mesajı'],['results_empty_text','Sonuçlar boş mesajı']];return `<div class="cardhead"><div><h3>Site Yazıları ve Banner</h3><p class="muted">Sitede görünen ana metinleri buradan değiştirebilirsin.</p></div></div><div class="settingsForm">${fields.map(([k,l])=>`<label>${l}${k.includes('text')||k.includes('subtitle')?`<textarea id="set_${k}">${esc(s[k]||'')}</textarea>`:`<input id="set_${k}" value="${esc(s[k]||'')}">`}</label>`).join('')}<button class="primary" id="saveSettings">Ayarları Kaydet</button></div>`}
async function saveSettings(){const payload={id:1,updated_at:new Date().toISOString()};Object.keys(defaults).forEach(k=>payload[k]=$('#set_'+k)?.value?.trim()||defaults[k]);const {error}=await db.from('election_settings').upsert(payload);if(error)return alert(error.message);alert('Site yazıları kaydedildi.');await load();}
function newElection(){modal(`<h3>Yeni Seçim</h3><input id="xTitle" placeholder="Seçim adı"><textarea id="xDesc" placeholder="Açıklama"></textarea><label>Başlangıç (Türkiye saati)</label><input id="xStart" type="datetime-local"><label>Bitiş (Türkiye saati)</label><input id="xEnd" type="datetime-local"><label>Durum</label><select id="xStatus"><option value="open">Açık (oluşturunca aktif olsun)</option><option value="draft">Taslak</option><option value="closed">Kapalı</option></select><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="save">Oluştur</button></div>`);$('#cancel').onclick=closeModal;$('#save').onclick=async()=>{const title=$('#xTitle').value.trim();if(!title)return alert('Seçim adı zorunlu.');const start=localToISO($('#xStart').value),end=localToISO($('#xEnd').value);if(start&&end&&new Date(end)<=new Date(start))return alert('Bitiş zamanı başlangıçtan sonra olmalı.');const {data,error}=await db.from('elections').insert({title,description:$('#xDesc').value.trim(),start_at:start,end_at:end,status:$('#xStatus').value}).select().single();if(error)return alert(error.message);state.selectedElectionId=data.id;closeModal();load()}}
function editElection(id){const e=state.elections.find(x=>x.id===id);modal(`<h3>Seçimi Düzenle</h3><input id="xTitle" value="${esc(e.title)}"><textarea id="xDesc">${esc(e.description||'')}</textarea><label>Başlangıç (Türkiye saati)</label><input id="xStart" type="datetime-local" value="${toLocalInput(e.start_at)}"><label>Bitiş (Türkiye saati)</label><input id="xEnd" type="datetime-local" value="${toLocalInput(e.end_at)}"><label>Durum</label><select id="xStatus"><option value="draft">Taslak</option><option value="open">Açık</option><option value="closed">Kapalı</option></select><label><input type="checkbox" id="xVisible" ${e.results_visible?'checked':''}> Sonuçları göster</label><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="save">Kaydet</button></div>`);$('#xStatus').value=e.status;$('#cancel').onclick=closeModal;$('#save').onclick=async()=>{const start=localToISO($('#xStart').value),end=localToISO($('#xEnd').value);if(start&&end&&new Date(end)<=new Date(start))return alert('Bitiş zamanı başlangıçtan sonra olmalı.');const {error}=await db.from('elections').update({title:$('#xTitle').value.trim(),description:$('#xDesc').value.trim(),start_at:start,end_at:end,status:$('#xStatus').value,results_visible:$('#xVisible').checked}).eq('id',id);if(error)return alert(error.message);closeModal();load()}}
function newCandidate(){const e=selectedElection();if(!e)return alert('Önce seçim oluştur.');modal(`<h3>Aday Ekle</h3><input id="xName" placeholder="Aday adı"><textarea id="xDesc" placeholder="Açıklama"></textarea><input id="xPhoto" placeholder="Fotoğraf URL (isteğe bağlı)"><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="save">Ekle</button></div>`);$('#cancel').onclick=closeModal;$('#save').onclick=async()=>{const {error}=await db.from('candidates').insert({election_id:e.id,name:$('#xName').value.trim(),description:$('#xDesc').value.trim(),photo_url:$('#xPhoto').value.trim()||null});if(error)return alert(error.message);closeModal();load()}}
function newVoter(){const e=selectedElection();if(!e)return alert('Önce seçim oluştur.');modal(`<h3>Oy Kullanıcı Ekle</h3><input id="xName" placeholder="Ad soyad"><input id="xMail" placeholder="E-posta (isteğe bağlı)"><input id="xCode" placeholder="Erişim kodu"><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="save">Ekle</button></div>`);$('#cancel').onclick=closeModal;$('#save').onclick=async()=>{const code=$('#xCode').value.trim();if(!code)return alert('Erişim kodu zorunlu.');const {error}=await db.from('voters').insert({election_id:e.id,name:$('#xName').value.trim(),email:$('#xMail').value.trim()||null,access_code:code});if(error)return alert(error.message);closeModal();load()}}
async function del(table,id){if(!confirm('Silmek istediğine emin misin?'))return;const {error}=await db.from(table).delete().eq('id',id);if(error)return alert(error.message);load()}
async function login(){modal(`<h3>Yönetici Girişi</h3><input id="email" type="email" placeholder="E-posta"><input id="password" type="password" placeholder="Şifre"><div class="actions"><button class="secondary" id="cancel">İptal</button><button class="primary" id="doLogin">Giriş</button></div>`);$('#cancel').onclick=closeModal;$('#doLogin').onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return alert(error.message);closeModal();load()}}
$$('.nav').forEach(b=>b.onclick=()=>{if(b.dataset.page==='admin'&&!state.user)return login();setPage(b.dataset.page)});$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};load();
